[package]
name = "cgit-simple-authentication"
version = "4.0.0-beta"
authors = ["KunoiSayami <i@leanhe.dev>"]
edition = "2018"

[dependencies]
anyhow = "1"
argon2 = "0.4"
async-trait = "0.1"
base64 = "0.13"
clap = "2.33"
env_logger = "0.8"
handlebars = "3.4"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_info"] }
log4rs = "1"
pam = "0.7.0"
rand = "0.7"
rand_core = { version = "0.6", features = ["std"] }
redis = { version = "0.21", features = ["tokio-comp"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", features = [ "json", "sqlite", "runtime-actix-native-tls"] }
tempdir = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
toml = "0.5"
url = "2.1"
uuid = { version = "0.8", features = ["v4"] }

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
cpufeatures = "0.1.3"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
