[package]
name = "cgit-simple-authentication"
version = "0.1.0"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
env_logger = "0.8"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde_derive = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
toml = "0.5"
syslog = "5.0.0"
sqlx = { version = "0.5", features = [ "json", "sqlite", "runtime-actix-native-tls"] }
rand = "0.7"
clap = "2.33"
handlebars = "3.4"
url = "2.1"
redis = { version = "0.17.0", features = ["tokio-comp"] }
sha2 = "0.9.3"
base64 = "0.13.0"