[package]
name = "cgit-simple-authentication"
version = "0.3.4"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
env_logger = "0.8"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde_derive = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
toml = "0.5"
sqlx = { version = "0.5", features = [ "json", "sqlite", "runtime-actix-native-tls"] }
rand = "0.7"
clap = "2.33"
handlebars = "3.4"
url = "2.1"
redis = { version = "0.17", features = ["tokio-comp"] }
base64 = "0.13"
log4rs = "1"
tokio-stream = "0.1"
argon2 = "0.2"
rand_core = "0.6"
uuid = { version = "0.8", features = ["v4"] }
tempdir = "0.3"
regex = "1"

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }